# These are manually repaired lines because they had a strange
# "i" -> "l '" OCR conversion error
df_i_to_l_apostrophe <- tibble::tribble(
  ~line,   ~index, ~batch,
  " (VACUUM CLEANER HUMS)  I'm 3O today,   My mum got me up really early this morning  to give me my present,  ", 3449345L,   115L,
  "A different angle.  These are your profits for this year,   And this is what you're doing  to those profits,,,   if you underestimate  the value of customer care,  ",  514839L,    18L,
  "A different angle.  These are your profits for this year,   And this is what you're doing  to those profits,,,   if you underestimate  the value of customer care,  ", 3883293L,   129L,
  "And, uh...    I I'm not sure I understand  how the way the world is changing  is actually going to change how we do business. ",  597878L,    20L,
  "Are you gonna take the marshal's appointment? ", 1940507L,    65L,
  "Bruce. Come down to the vault room right away.  What for? -Hill's on the phone...   ... wants to talk to you.  Says it's important.  ", 2321942L,    77L,
  "But I I'm okay.  I'm glad you're okay. ",  170202L,     6L,
  "But I I've been doing a lot of thinking, too,  and I'm  taking anthropology classes. ", 2711592L,    90L,
  "Con told me Laurel was here.  All right, fella, that's one on me. No, she's here!  Hey, Laurel's here, isn't she? Yes. Won't you stay for dinner? ", 4930812L,   164L,
  "Don't pull 'em. They pop and have little hats inside.  And little baskets. I put candies in with the nuts. ", 3014734L,   100L,
  "Fine! But what's wrong with that?  (GARETH) Yeah, I feel sorry for Dawn and Lee,   If they have to call off the wedding,,,   then I'm sure it'll be upsetting now,  but in the end, it's for the best. ", 3742955L,   124L,
  "Fine! But what's wrong with that?  (GARETH) Yeah, I feel sorry for Dawn and Lee,   If they have to call off the wedding,,,   then I'm sure it'll be upsetting now,  but in the end, it's for the best. ", 5959802L,   198L,
  "Good bloke. Good laugh.  David, it's Paul again,,,  ", 3542575L,   118L,
  "Good bloke. Good laugh.  David, it's Paul again,,,  ", 4113147L,   137L,
  "Hey! Um,  just reading. I I've-- I go to NYU now. ",    516074L,    18L,
  "Hey, what bike you got?  A Matchless 5OO. Is that a Harley Davidson?  I love all that. Leave it.  (TIM) Slough's nightlife is incredible,   It's got two nightclubs - Chasers   and New York New York,  ", 1342185L,    45L,
  "Hey, what bike you got?  A Matchless 5OO. Is that a Harley Davidson?  I love all that. Leave it.  (TIM) Slough's nightlife is incredible,   It's got two nightclubs - Chasers   and New York New York,  ", 5762813L,   191L,
  "Hooray.  See you later. Yeah.  (DAWN) I hope they get rid of me,  ", 1793925L,    60L,
  "Hooray.  See you later. Yeah.  (DAWN) I hope they get rid of me,  ", 5328010L,   177L,
  "I mean, you can... It's like I was good at it before I was trained,  but now I'm trained I'm better than people who weren't good before.  Today's our staff training,  ",  245454L,     9L,
  "I mean, you can... It's like I was good at it before I was trained,  but now I'm trained I'm better than people who weren't good before.  Today's our staff training,  ", 3438271L,   114L,
  "I've got a sense of humour, but that was offensive towards women,  and I can't tolerate that. I'll have to pass on...  The time sponsored by Accurist will be 4,21   and 4O seconds,   Pathetic. Is it?  At the third stroke,  the time sponsored by Accurist   will be 4,21 and 5O seconds,  ", 2515605L,    84L,
  "I've got a sense of humour, but that was offensive towards women,  and I can't tolerate that. I'll have to pass on...  The time sponsored by Accurist will be 4,21   and 4O seconds,   Pathetic. Is it?  At the third stroke,  the time sponsored by Accurist   will be 4,21 and 5O seconds,  ", 4706045L,   156L,
  "Kendall's was my first real job. ", 3328292L,   111L,
  "Laurel's here.  When did she get back? She was here when I got here.  How do you do, Mrs. Dallas? Hello, Dick.  I'm glad to see you again. I'm glad to see you. ",  237238L,     8L,
  "Laurel's such a lovely child.", 1037142L,    35L,
  "Listen, smart-ass. I don't like it. I don't like it.  I don't like it one bit. Deal's off.  Just like that? Yeah. You got a problem with that?  Sorry I'm late, Earl. Mikey. What the fuck? ",  112551L,     4L,
  "MAN 2: Look at that, Simon & Garfunkel's Greatest Hits.  ",  785018L,    26L,
  "My girl's got a taste for nice things  and I can't afford to let her down :  ",  759313L,    26L,
  "No!  Dave, it's Julian, Can you give us a ring, please?  ",  483389L,    16L,
  "No!  Dave, it's Julian, Can you give us a ring, please?  ",  693390L,    23L,
  "No. It's illegal to destroy or burn anything  containing the Queen's image of the realm.  Can we just watch the video? Yeah. That's true.  Statistics show that if you're  treated well as a customer   you'll tell five people,   If you're treated badly, you'll tell nine,   So can you set fire to a stamp? No. ", 1801201L,    60L,
  "No. It's illegal to destroy or burn anything  containing the Queen's image of the realm.  Can we just watch the video? Yeah. That's true.  Statistics show that if you're  treated well as a customer   you'll tell five people,   If you're treated badly, you'll tell nine,   So can you set fire to a stamp? No. ", 5916493L,   196L,
  "No. Not up the arse.  (DAVID ) This is the poem \"Slough\"  by Sir John Betjeman,   Probably never been here,   \"Come, friendly bombs, and fall on Slough.  \"It isn't fit for humans now.\" ", 4390969L,   146L,
  "No. Not up the arse.  (DAVID) This is the poem \"Slough\"  by Sir John Betjeman,   Probably never been here,   \"Come, friendly bombs, and fall on Slough.  \"It isn't fit for humans now.\" ",  653689L,    22L,
  "Not only is it derogatory...  David has trusted me with this because,,,   not only have I got people skills,   but I am trained in covert operations,  ",  476514L,    16L,
  "Not only is it derogatory...  David has trusted me with this because,,,   not only have I got people skills,   but I am trained in covert operations,  ", 1282915L,    43L,
  "Oh, God...  Yeah, There are limits to my comedy,  ", 1308444L,    44L,
  "One more drink. # Life! Oh, life!  # Oh, life! # Don't do that.  \"Come, friendly bombs, and fall on Slough,   \"to get it ready for the plough,   \"The cabbages are coming now.  \"The earth exhales...\" He's the only cabbage.  # So what becomes of you, my love,  # When they have finally stripped you of  # The handbags and the gladrags  # That your granddad had to sweat so you could buy. # ", 2773469L,    92L,
  "One more drink. # Life! Oh, life!  # Oh, life! # Don't do that.  \"Come, friendly bombs, and fall on Slough,   \"to get it ready for the plough,   \"The cabbages are coming now.  \"The earth exhales...\" He's the only cabbage.  # So what becomes of you, my love,  # When they have finally stripped you of  # The handbags and the gladrags  # That your granddad had to sweat so you could buy. # ", 4632300L,   154L,
  "Philosophy.  (ElGHTIES-STYLE \"DYNAMIC\" MUsiC)  Hi,   What's the single most important thing  to your business?   Staff. That's right, The customer,  ", 4795052L,   159L,
  "Philosophy.  (ElGHTIES-STYLE \"DYNAMIC\" MUsiC)  Hi,   What's the single most important thing  to your business?   Staff. That's right, The customer,  ", 5992302L,   199L,
  "Pot Noodle and a wank!  (TIM) I don't know  where we're going tonight,   Obviously, Finchy's a sophisticated guy,   and Gareth's a culture vulture,  ",  749524L,    25L,
  "Pot Noodle and a wank!  (TIM) I don't know  where we're going tonight,   Obviously, Finchy's a sophisticated guy,   and Gareth's a culture vulture,  ", 5703065L,   189L,
  "Sorry, I don't speak Italian.  I am Federico Fabrizi. I'm Harry Granoff.  I'm Mr. Powell's manager. It's so nice to see you. ", 2305637L,    77L,
  "That Jenkins girl's just dyin' to get him. ", 1332520L,    45L,
  "This got anything to do with the girl's murder? ",  942801L,    32L,
  "Three.  David, Paul Shepherd, Can you give us a call?  ", 3211433L,   107L,
  "Three.  David, Paul Shepherd, Can you give us a call?  ", 4287624L,   142L,
  "We are the most efficient branch -  cogito ergo sum - we'll be fine.  Why should they be worried, yeah?   They trust me implicitly,  ",    8901L,     1L,
  "We are the most efficient branch -  cogito ergo sum - we'll be fine.  Why should they be worried, yeah?   They trust me implicitly,  ",  790151L,    27L,
  "Where the hell's Blanchard? ",  280114L,    10L,
  "Why's he got a... ? Doesn't he like girls?  \"And talk of sports and makes of cars  in various bogus Tudor bars,   \"and daren't look up and see the stars,  but belch instead, \"   What's he on about? He's never burped?   Where are we going? What? I'm going home, mate.  One more drink. I'm going home, David. ", 1727446L,    58L,
  "Why's he got a... ? Doesn't he like girls?  \"And talk of sports and makes of cars  in various bogus Tudor bars,   \"and daren't look up and see the stars,  but belch instead, \"   What's he on about? He's never burped?   Where are we going? What? I'm going home, mate.  One more drink. I'm going home, David. ", 5704747L,   189L,
  "You don't solve town planning problems by dropping bombs,  so he's embarrassed himself there.  \"In labour-saving homes with care   \"Their wives frizz out peroxide hair,   \"and dry it in synthetic air,  and paint their nails, \" To look nice,  ",   97230L,     4L,
  "You don't solve town planning problems by dropping bombs,  so he's embarrassed himself there.  \"In labour-saving homes with care   \"Their wives frizz out peroxide hair,   \"and dry it in synthetic air,  and paint their nails, \" To look nice,  ", 4121930L,   137L
)
